task_info:
  raw_dataset_directory: /dfs3b/ruic20_lab/jinl14/mrrdir/wkfl/hrcaprj/HRCA/CAP/fix_donor/scrnah5adobssubset2replacebydict/HRCA_snRNA_allcells_rawcounts.h5ad
  raw_dataset_name: eyeGPT
  save_dir: save/pp_eyeGPT-Nov10-02-12-34
  input_dataset_directory: save/pp_eyeGPT-Nov10-02-12-34/input_data.h5ad
  id2type_json: save/pp_eyeGPT-Nov10-02-12-34/id2type.json
preprocess:
  do_norm: true
  filter_gene_by_counts: 0
  filter_cell_by_counts: 0
  normalize_total: 10000
  n_hvg: 5000
  hvg_flavor: seurat_v3
  dataset_cell_type_col: celltype
  dataset_batch_id_col: sampleid
  _FIXED_BATCH_ID_COL: batch_id
  _FIXED_CELL_TYPE_COL: celltype
  _FIXED_CELL_TYPE_ID_COL: celltype_id
  _FIXED_GENE_COL: gene_name
model_parameters:
  seed: 0
  load_model: /pub/rluo5/pretrained_models/scgpt_human
  do_train: true
  epochs: 1
  use_flash_attn: false
  fast_transformer_backend: flash
  use_batch_labels: false
  pre_norm: false
  DSBN: false
  amp: true
  freeze_predecoder: false
  train_test_split_ratio: 0.1
  batch_size: 12
  lr: 1.0e-05
  dropout: 0.1
  schedule_ratio: 0.9
  schedule_interval: 1
  log_interval: 100
  save_eval_interval: 1
  nlayers: 12
  nheads: 8
  embsize: 512
  d_hid: 512
  nlayers_cls: 7
  use_weighted_loss: false
wandb_configs:
  mode: offline
  project: '3_1'
  reinit: true
  name: ''
task_configs:
  pad_token: <pad>
  cls_token: <cls>
  eoc_token: <eoc>
  mask_value: -1
  pad_value: -2
  CLS: true
  MVC: false
  mask_ratio: 0
  MLM: false
  ADV: false
  CCE: false
  ECS: false
  ecs_threshold: 0.0
  DAB: false
  dab_weight: 0.0
  max_seq_len: 5001
  n_input_bins: 51
  input_style: binned
  input_emb_style: continuous
  cell_emb_style: cls
  append_cls: true
  include_zero_gene: false
  sort_per_seq_batch: false
  explicit_zero_prob: false
  do_sample_in_train: false
