model_parameters:
  DSBN: false
  batch_size: 32
  d_hid: 512
  do_train: false
  dropout: 0.1
  embsize: 512
  epochs: 1
  fast_transformer_backend: flash
  freeze_predecoder: false
  load_model: models/test_model
  log_interval: 10
  lr: 0.001
  nheads: 8
  nlayers: 6
  nlayers_cls: 2
  pre_norm: false
  save_eval_interval: 1
  schedule_interval: 1
  seed: 42
  use_batch_labels: false
  use_flash_attn: false
preprocess:
  _FIXED_BATCH_ID_COL: batch_id
  _FIXED_CELL_TYPE_COL: cell_type
  _FIXED_CELL_TYPE_ID_COL: cell_type_id
  _FIXED_GENE_COL: gene_name
  dataset_batch_id_col: null
  dataset_cell_type_col: null
  do_norm: true
  filter_cell_by_counts: 0
  filter_gene_by_counts: 0
  hvg_flavor: seurat_v3
  n_hvg: 5000
  normalize_total: 10000
task_configs:
  CLS: true
  DAB: false
  MVC: true
  append_cls: true
  cell_emb_style: cls
  cls_token: <cls>
  ecs_threshold: 0.8
  eoc_token: <eoc>
  include_zero_gene: false
  input_emb_style: continuous
  mask_value: -1
  max_seq_len: 2000
  n_input_bins: 5
  pad_token: <pad>
  pad_value: 0
task_info:
  id2type_json: ''
  input_dataset_directory: ''
  raw_dataset_directory: ''
  raw_dataset_name: test_dataset
  save_dir: ''
wandb_configs:
  mode: offline
  name: test_run
  project: test_project
  reinit: true
